### ISSUE TITLE
Create browser wallet to demonstrate bls client module

### ISSUE THREAD

**Issue by blakecduncan** [jzaki/bls-wallet#290] opened 2022-08-01 08:45 UTC
Create a simple webpage that integrates the bls client module to demonstrate a simple integration.

**Comment by jzaki** [comment] 2022-08-22 07:11
So far we've seen: sending ethers, and multi-action user operations.
Last thing to add might be the recovery path:

- setting the recovery hash (hash of recovery wallet address and salt) 
- from recovery wallet, call recover with salt and new bls key

Feel free to create a separate issue for recovery, since I think this one is nearly complete

**Comment by blakecduncan** [comment] 2022-08-22 07:49
Nice, thanks for this @jzaki .  Do you know of any examples out there that do this already that I can check out how they do the UX?

**Comment by jacque006** [comment] 2022-10-26 18:59
@blakecduncan Has this been completed with https://github.com/blakecduncan/bls-browser-wallet ?

**Comment by jacque006** [comment] 2022-10-26 19:59
Confirmed, closing. We can consider transferring the repo in https://github.com/web3well/bls-wallet/issues/359

**Closed as completed by jacque006** 2022-10-26 19:59 UTC
Labels: enhancement, clients
